#!/bin/bash

PROJECT_DIR="$(dirname $0)/../"
NEW_NAME="$1"

if (( "$#" != 1 )); then
	echo 'Usage Info: '
	echo 'tools/renameProject "myNewName"'
	echo 'Your new filename must be contain at least 3 and only upper- and lowercase letters!'
	exit 1
fi

if [[ $NEW_NAME =~ "[a-z|A-Z]{3,}" ]]; then
	echo "### Your new filename must be contain at least 3 and only upper- and lowercase letters ###"
	exit 0	
fi

FILES_TO_RENAME="$(grep -ril 'MyPlugin' . |egrep -v "JUCE/modules|JUCE/extras|README|External|additional_modules|$(basename $0)" |xargs)"

if [ -z "$FILES_TO_RENAME" ]; then
	echo "At the moment your can only rename your Project once"
fi

sed -i '' -e "s/MyPlugin/$NEW_NAME/g" $FILES_TO_RENAME

find . -name "*MyPlugin*" -exec rename 's/MyPlugin/$(echo "$NEW_NAME")/' '{}' \;